### ISSUE TITLE
.auto() yields tmax == tmin, and negative remaining time

### ISSUE THREAD

**Issue by kim0** [perrygeo/simanneal#10]
Running .auto() in a script output the following
```
 Temperature        Energy    Accept   Improve     Elapsed   Remaining
        0.21         21.00   100.00%     0.00%     0:00:10    -1:59:50
{u'tmax': 0.21, u'tmin': 0.21, u'steps': 310000000.0}
```

I'm new to all of this .. Just wondering if this is a bug, or if it can make sense sometimes ?

**Comment by perrygeo** [comment]
Can you provide the code to reproduce this?

**Comment by kim0** [comment]
Unfortunately I don't think I can .. I think however this might have been during an early stage, where I wrote a faulty .move() that was not changing .. so I guess maybe disregard this
