### ISSUE TITLE
Allow any type of state variable

### ISSUE THREAD

**Issue by matsulib** [perrygeo/simanneal#19]
I could use type numpy.ndarray or pandas.DataFrame for state variable from #12.
Unfortunately, the patch of #12 was canceled by https://github.com/perrygeo/simanneal/commit/ed975245a7849a6cbe674bd52fde1fce14512774.
There seems to be a little confusion.

I have a suggestion about this code.
```python
class Annealer(object):
    def __init__(self, initial_state=None, load_state=None):
        if initial_state:
            self.state = self.copy_state(initial_state)
        elif load_state:
            with open(load_state, 'rb') as fh:
                self.state = pickle.load(fh)
        else:
            raise ValueError('No valid values supplied for neither \
            initial_state nor load_state')
```
To start annealing, I think only two things are required in `__init__()`.
First, either `initial_state `or `load_state` is given.
Second, the given object is copyable. The definition of "copyable" can be custmized by overriding `copy_state()`.

Therefore, all we have to do in `__init__()` is to check whether `initial_state` is given or not.
Other conditions about state can be handled by `move()` and `energey()`, so it doesn't matter if `initial_state ` itself is evaluated as false like an empty list.

**Comment by perrygeo** [comment]
fixed by #20
