### ISSUE TITLE
multithreading

### ISSUE THREAD

**Issue by DonGiulio** [perrygeo/simanneal#25]
This algorithm can be quite time consuming, and it could benefit greatly from multithreading, 

I'm not sure how this could be achieved, in sight of the fact that the original algorithm considers just one solution per time, maybe, because the next moves are independent from the next temperature, one could calculate some of the next moves, so that the results might come much faster. 

of course there might be some wasted computation, but there would be a good improvement on running speed regardless. 

your thoughts? 
Thanks

**Comment by perrygeo** [comment]
There is a large body of research into parallelizing simulated annealing that is pretty interesting but  largely outside the scope of this module. The primary goal here is readability and fast prototyping. If performance is your goal, I'd recommend writing a custom implementation in C to explore some of these 

That said, if you can find a general purpose technique to speed up SA with multithreading in Python, I'd be happy to review a PR.
