### ISSUE TITLE
Litterature reference for simulated annealing

### ISSUE THREAD

**Issue by ZhiWeiCui** [perrygeo/simanneal#43]
Thank you so much for providing an amazing package.

I want to know which literature  you have referenced to implement the simulated annealing algorithm.  

Because I checked the original related literature of this algorithm, it usually contains two loops: an inner loop and an outer loop.  

I want to know more about this literature .

E.g: Gendreau, Michel, Jean-Yves Potvin, and others. Handbook of Metaheuristics. Vol. 2. Springer, 2010.

![Snipaste_2021-04-16_15-57-33](https://user-images.githubusercontent.com/22850130/114991766-8bbf0200-9ecc-11eb-9446-7482b6cd49d6.png)

**Comment by haolimin01** [comment]
I have the same question.

**Comment by perrygeo** [comment]
I did not reference any literature to implement this. Most of the simulated annealing literature of the last few decades involves more advanced techniques and refinements. The basic SA algorithm (effectively the inner loop you're referencing) was the goal and is trivially simple. As your diagram clearly shows, it is also trivially simple to wrap the inner loop inside an outer loop that implements your domain-specific stopping criteria. From a software design perspective, that logic belongs in the application not the library, as users should have full freedom to implement their own stopping criteria.
