### ISSUE TITLE
Speeding Up the Calculation

### ISSUE THREAD

**Issue by uqhwen2** [perrygeo/simanneal#48]
I'm wondering how can we do to leverage multiple CPUs when doing the annealing algorithm? I try to use GPU for quicker calculation, but it seems does not offer any help :(.

I notice that when I run this code, it only takes up 1 CPU, but my other learning algorithm like simple neural network can take up multiple CPUs to accelerate the calculation.

Thanks for any reply.

Cheers.

**Comment by perrygeo** [comment]
The simulated annealing algorithm is inherently serial - each iteration strictly depends on the result of the previous. You can check the literature for "parallel simulated annealing" - there are plenty of good ideas. But this library is focused on experimentation with the classic simulated annealing algorithm. If performance is your goal, you're better off writing it in another language entirely.

Another alternative is to e.g. create an ensemble of runs that can be executed in parallel.

**Comment by uqhwen2** [comment]
Thanks mate, I really appreciate your helpful comments! 

Best regard,
HW
