### ISSUE TITLE
Replacing lines to shorten output

### ISSUE THREAD

**Issue by straningera** [perrygeo/simanneal#7]
Hi. I'm using the simulated annealing part several times in my scripts. The console output is too long for my task, so I changed the print statements in lines 86 et seqq. to the following:

            sys.stdout.write('\r%12.2f  %12.2f                      %s            ' % \
                (T, E, time_string(elapsed)))
            sys.stdout.flush()
 
and 

            sys.stdout.write('\r%12.2f  %12.2f  %7.2f%%  %7.2f%%  %s  %s' % \
                (T, E, 100.0 * acceptance, 100.0 * improvement,
                    time_string(elapsed), time_string(remain))),
            sys.stdout.flush()

By doing so, previous outputs are replaced by the most recent output.

**Comment by kim0** [comment]
@perrygeo .. Guess this was merged and should be closed!
